#pragma once

namespace Slic3r::App {

enum class MenuItemName
{
    Separator,
    MainMenu,

    Edit,
    SelectAll,
    DeselectAll,
    DeleteSelected,
    Undo,
    Redo,
    Copy,
    Paste,
    ReloadFromDisk,
    Search,

    ShapeGallery,

    View,
    ShowLabel,
    FullScreen,
    ZoomIn,
    ZoomOut,
    CameraProjectionSwitch,
    LookAtActiveBed,
    CameraDefaultView,
    CameraTopView,
    CameraBottomView,
    CameraFrontView,
    CameraRearView,
    CameraLeftView,
    CameraRightView,

    Preferences,

    Configuration,
    ConfigurationWizard,
    CheckConfigUpdates,
    CheckAppUpdates,
    FlashPrinterFirmware,

    Help,
    PSWebsite,
    QuickStart,
    Samples,
    Prusa3DDrivers,
    Releases,
    SystemInfo,
    ConfigFolder,
    ReportAnIssue,
    About,
    TipOfTheDay,
    KeyboardShortcutsDialog,

    Exit,

    FileMenu,
    NewProject,
    OpenProject,
    SaveProject,
    SaveProjectAs,

    RecentProjects,

    Import,
    ImportGeometry,

    Export,
    ExportGcode,
    SendGcode,
    ExportGcodeToFlash,

    OnlinePresetUpdate,

    JumpToValue,

    BedContextMenu,
    AddObjectShape,
    ObjectShapeLoad,
    ObjectShapeCube,
    ObjectShapeCylinder,
    ObjectShapeSphere,
    ObjectShapeText,
    ObjectShapeSvg,
    ObjectShapeFromGallery,
    ArrangeBed,
    SelectAllOnBed,
    DeleteBed,

    ObjectContextMenu,
    CopyObject,
    PasteObject,
    DeleteSelectedObject,
    SetNumberOfInstances,
    FillBedWithInstances,
    ExportObject,
    ReplaceObject,
    ReloadObject,
    SplitObject,
    SplitObjectToObjects,
    SplitObjectToVolumes,
    ScaleToPrintVolume,
    FixObjectWithRepairAlgorithm,
    AddVolume,
    SolidPartVolume,
    NegativeVolume,
    ModifierVolume,
    SupportBlocker,
    SupportModifier,
    SolidPartVolumeShapeLoad,
    SolidPartVolumeShapeCube,
    SolidPartVolumeShapeCylinder,
    SolidPartVolumeShapeSphere,
    SolidPartVolumeShapeText,
    SolidPartVolumeShapeSVG,
    SolidPartVolumeShapeFromGallery,
    NegativeVolumeShapeLoad,
    NegativeVolumeShapeCube,
    NegativeVolumeShapeCylinder,
    NegativeVolumeShapeSphere,
    NegativeVolumeShapeText,
    NegativeVolumeShapeSVG,
    NegativeVolumeShapeFromGallery,
    ModifierVolumeShapeLoad,
    ModifierVolumeShapeCube,
    ModifierVolumeShapeCylinder,
    ModifierVolumeShapeSphere,
    ModifierVolumeShapeSVG,
    ModifierVolumeShapeText,
    ModifierVolumeShapeFromGallery,
    SupportBlockerShapeLoad,
    SupportBlockerShapeCube,
    SupportBlockerShapeCylinder,
    SupportBlockerShapeSphere,
    SupportBlockerShapeFromGallery,
    SupportModifierShapeLoad,
    SupportModifierShapeCube,
    SupportModifierShapeCylinder,
    SupportModifierShapeSphere,
    SupportModifierShapeFromGallery,
    InvalidateCutInfo,
    PrintableObject,

    InstanceContextMenu, // for single and multi selected instances from same object
    DeleteSelectedInstance,
    SetAsSeparateObject,
    PrintableInstance,

    MultiObjectsContextMenu,
    CopyMultiObjects,
    DeleteSelectedMultiObjects,
    SetMultiObjectsNumberOfInstances,
    MergeMultiObjects,
    FixMultiObjectWithRepairAlgorithm,
    PrintableMultiObjects,

    SvgOrTextContextMenu,
    EditSvgOrText,
    DeleteSelectedSvgOrText,

    VolumeContextMenu,
    CopyVolume,
    PasteVolume,
    DeleteSelectedVolume,
    ExportVolume,
    ReplaceVolume,
    ReloadVolume,
    SplitVolume,
    FixVolumeWithRepairAlgorithm,
    ChangeVolumeType,
};
} // namespace Slic3r::App
