#include "Slic3r/Biz/Algorithms/Bed.hpp"
#include "Slic3r/Biz/Algorithms/Polygon.hpp"
#include "Slic3r/Biz/Algorithms/ExPolygon.hpp"
#include "Slic3r/Biz/Algorithms/BoundingBox.hpp"
#include "Slic3r/Biz/Algorithms/Geometry/ConvexHull.hpp"
#include "Slic3r/Biz/Algorithms/Scaling.hpp"
#include "Slic3r/Biz/Algorithms/Point.hpp"
#include "Slic3r/Math.hpp"
#include "Slic3r/Assert.hpp"

namespace Slic3r::Biz::Algorithms::Bed {

Domain::BedType detect_bed_type(const Domain::Bed& bed)
{
    //
    // See BuildVolume constructor as reference.
    //

    const Domain::Vec2ds& contour = bed.contour();
    if (contour.size() < 3)
        return Domain::BedType::Invalid;

    // Calculate various metrics of the input polygon.
    Domain::Polygon polygon      = Polygon::scaled(contour);
    Domain::Polygon convex_hull  = Geometry::convex_hull(polygon);
    Domain::BoundingBox2crd bbox = Polygon::get_extents(convex_hull);
    Domain::Vec2crd bbox_size    = BoundingBox::sizes(bbox);
    double area                  = polygon.area();
    double bbox_area             = double(bbox_size.x()) * double(bbox_size.y());

    if (contour.size() >= 4 && std::abs(area - bbox_area) < sqr(Domain::SCALED_EPSILON))
        return Domain::BedType::Rectangle;
    else if (contour.size() > 3) {
        Geometry::Circled circle = as_circular_bed(bed);
        if (circle.radius > 0.0)
            return Domain::BedType::Circle;
    }

    return ((convex_hull.area() - area) < sqr(Domain::SCALED_EPSILON)) ? Domain::BedType::Convex : Domain::BedType::Custom;
}

Geometry::Circled as_circular_bed(const Domain::Bed& bed)
{
    const Domain::Vec2ds& contour = bed.contour();
    Geometry::Circled circle      = Geometry::circle_ransac(contour);
    bool is_circle                = true;
    Domain::Vec2d prev            = contour.back();
    for (const Domain::Vec2d& p : contour) {
        if (// Polygon vertices must lie very close the circle.
            std::abs((p - circle.center).norm() - circle.radius) > 0.005 ||
            // Midpoints of polygon edges must not undercat more than 3mm. This corresponds to 72 edges per circle generated by BedShapePanel::update_shape().
            circle.radius - (0.5 * (prev + p) - circle.center).norm() > 3.0)
        {
            is_circle = false;
            break;
        }
        prev = p;
    }
    return is_circle ? circle : Geometry::Circled(Domain::Vec2d(0.0, 0.0), 0.0);
}

static Domain::Vec2ds aabb_corners(const Domain::BoundingBox2d& aabb, const Domain::Vec2d& offset)
{
    return {
        offset + aabb.min,
        offset + Domain::Vec2d(aabb.max.x(), aabb.min.y()),
        offset + aabb.max,
        offset + Domain::Vec2d(aabb.min.x(), aabb.max.y())
    };
}

static std::vector<Domain::Vec2crd> scaled_aabb_corners(const Domain::BoundingBox2d& aabb, const Domain::Vec2d& offset)
{
    return {
        Scaling::scaled(offset + aabb.min),
        Scaling::scaled(offset + Domain::Vec2d(aabb.max.x(), aabb.min.y())),
        Scaling::scaled(offset + aabb.max),
        Scaling::scaled(offset + Domain::Vec2d(aabb.min.x(), aabb.max.y()))
    };
}

BedContainmentState contains_2d(const Domain::BedInstance& bed_instance, const Domain::BoundingBox2d& object_bb)
{
    const Domain::Bed& bed = bed_instance.bed.get();
    Domain::Vec2d inst_pos = Point::to_2d(bed_instance.transformation.get_offset());

    switch (bed.type()) {
    default:
    case Domain::BedType::Invalid: {
        PANIC("Found invalid bed");
        return BedContainmentState::Outside;
    }
    case Domain::BedType::Rectangle: {
        Domain::Vec2d half_extent = 0.5 * bed.contour_aabb_extent();
        Domain::Vec2d center      = bed.center() + inst_pos;
        Domain::BoundingBox2d bed_bounds{center - half_extent, center + half_extent};
        return bed_bounds.contains(object_bb) ?
            BedContainmentState::Inside :
            bed_bounds.overlap(object_bb) ?
            BedContainmentState::Colliding :
            BedContainmentState::Outside;
    }
    case Domain::BedType::Circle: {
        std::optional<Domain::Bed::Circle> bed_circle = bed.circle();
        DEBUG_ASSERT(bed_circle.has_value());

        Geometry::Circle circle     = Geometry::Circle{bed_circle->first, bed_circle->second};
        Domain::Vec2ds bbox_corners = aabb_corners(object_bb, -inst_pos);
        size_t inside_count         = 0;
        for (const auto& v : bbox_corners) {
            if (circle.contains(v))
                ++inside_count;
        }
        return (inside_count == 0) ?
            BedContainmentState::Outside :
            (inside_count == bbox_corners.size()) ?
            BedContainmentState::Inside :
            BedContainmentState::Colliding;
    }
    case Domain::BedType::Convex: {
        std::optional<Domain::Bed::TopBottomDecomposition> convex_hull_decomposition = bed.top_bottom_convex_hull_decomposition();
        DEBUG_ASSERT(convex_hull_decomposition.has_value());

        Domain::Vec2ds bbox_corners = aabb_corners(object_bb, -inst_pos);
        size_t inside_count         = 0;
        for (const auto& v : bbox_corners) {
            if (Geometry::inside_convex_polygon(*convex_hull_decomposition, v))
                ++inside_count;
        }
        return (inside_count == 0) ?
            BedContainmentState::Outside :
            (inside_count == bbox_corners.size()) ?
            BedContainmentState::Inside :
            BedContainmentState::Colliding;
    }
    case Domain::BedType::Custom: {
        // WARNING !!
        // The following algorithm is NOT robust as a non convex polygon could contain all the vertices
        // of the box without fully containing the box itself.

        Domain::ExPolygon expolygon(Polygon::scaled(bed.contour()));

        std::vector<Domain::Vec2crd> bbox_corners = scaled_aabb_corners(object_bb, -inst_pos);
        size_t inside_count                       = 0;
        for (const auto& v : bbox_corners) {
            if (ExPolygon::contains(expolygon, v))
                ++inside_count;
        }
        return (inside_count == 0) ?
            BedContainmentState::Outside :
            (inside_count == bbox_corners.size()) ?
            BedContainmentState::Inside :
            BedContainmentState::Colliding;
    }
    }
}

BedContainmentState contains_3d(const Domain::BedInstance& bed_instance, const Domain::BoundingBox3d& object_bb)
{
    BedContainmentState state = contains_2d(bed_instance, BoundingBox::to_2d(object_bb));
    if (state != BedContainmentState::Inside)
        return state;

    if (object_bb.max.z() < 0.0)
        return BedContainmentState::Below;
    const Domain::Bed& bed = bed_instance.bed.get();
    if (object_bb.min.z() > bed.max_print_height())
        return BedContainmentState::Outside;
    else if (object_bb.max.z() > bed.max_print_height())
        return BedContainmentState::Colliding;
    else
        return BedContainmentState::Inside;
}

} // namespace Slic3r::Biz::Algorithms::Bed
