///|/ Copyright (c) Prusa Research 2020 - 2023 Lukáš Matěna @lukasmatena, Oleksandra Iushchenko @YuSanka, Enrico Turri @enricoturri1966, Tomáš Mészáros @tamasmeszaros, Lukáš Hejl @hejllukas
///|/
///|/ PrusaSlicer is released under the terms of the AGPLv3 or higher
///|/
#include "Slic3r/App/Scene/Clipper.hpp"

#include "Slic3r/App/Scene/Camera.hpp"
#include "Slic3r/App/Scene/Ray.hpp"

#include "Slic3r/Domain/ModelObject.hpp"
#include "Slic3r/Domain/TriangleMesh.hpp"

#include "Slic3r/Biz/Algorithms/BoundingBox.hpp"
#include "Slic3r/Biz/Algorithms/ModelObject.hpp"

namespace Slic3r::App::Scene {

using namespace Slic3r::Domain;
using namespace Slic3r::Biz::Algorithms;

void Clipper::set_camera(const Camera* camera)
{
    m_camera = camera;
}

void Clipper::update(
    const Domain::ModelObject* selected_object,
    const Domain::ModelInstance* selected_instance,
    double sla_shift,
    bool force_clipper_regeneration
)
{
    m_selected_object   = selected_object;
    m_selected_instance = selected_instance;
    m_sla_shift         = sla_shift;

    if (!m_selected_object || !m_selected_instance)
        return;

    // which mesh should be cut?
    std::vector<const Domain::TriangleMesh*> meshes;
    std::vector<Transformation> trafos;

    std::unique_ptr<Biz::MeshClipper> mc;
    Transformation mc_tr;
    // if (wxGetApp().preset_bundle->printers.get_selected_preset().printer_technology() == ptSLA) {
    // // For sla printers we use the mesh generated by the backend
    // const SLAPrintObject* po = get_pool()->selection_info()->print_object();
    // if (po) {
    // auto partstoslice = po->get_parts_to_slice();
    // if (!partstoslice.empty()) {
    // mc = std::make_unique<Biz::MeshClipper>();
    // mc->set_mesh(range(partstoslice));
    // mc_tr = Transformation{po->trafo().inverse().cast<double>()};
    // }
    // }
    //}

    if (!mc && meshes.empty()) {
        for (const Domain::ModelVolume* mv : m_selected_object->volumes) {
            meshes.emplace_back(&mv->mesh());
            trafos.emplace_back(mv->get_transformation());
        }
    }

    if (mc || force_clipper_regeneration || meshes != m_old_meshes) {
        object_clippers.clear();
        for (size_t i = 0; i < meshes.size(); ++i) {
            object_clippers.emplace_back(new Biz::MeshClipper, trafos[i]);
            object_clippers.back().first->set_mesh(meshes[i]->its);
        }
        m_old_meshes = std::move(meshes);

        if (mc) {
            object_clippers.emplace_back(std::move(mc), mc_tr);
        }

        Domain::Vec3d bb_size = Biz::Algorithms::BoundingBox::sizes(
            Biz::Algorithms::ModelObject::instance_bounding_box(
                *m_selected_object,
                *m_selected_instance
            )
        );

        m_active_inst_bb_radius = 0.5 * bb_size.norm();
    }

    recalculate_object_clippers();
}

void Clipper::release()
{
    object_clippers.clear();
    m_old_meshes.clear();
    m_clp.reset();
    m_clp_ratio = 0.;
}

void Clipper::recalculate_object_clippers()
{
    if (m_clp_ratio == 0.)
        return;
    const Transformation inst_trafo = m_selected_instance->get_transformation();

    for (auto& clipper : object_clippers) {
        Transformation trafo = inst_trafo * clipper.second;
        trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., m_sla_shift));
        clipper.first->set_plane(*m_clp);
        clipper.first->set_transformation(trafo);
        clipper.first->set_limiting_plane(Biz::ClippingPlane(Vec3d::UnitZ(), -SINKING_Z_THRESHOLD));
        clipper.first->update_result();
    }
}

const std::vector<Domain::ModelVolume*>& Clipper::volumes()
{
    assert(m_selected_object);
    return m_selected_object->volumes;
}

int Clipper::get_number_of_contours() const
{
    int sum = 0;
    for (const auto& [clipper, trafo] : object_clippers)
        sum += clipper->get_number_of_contours();
    return sum;
}

int Clipper::is_projection_inside_cut(const Vec3d& point) const
{
    if (m_clp_ratio == 0.)
        return -1;
    int idx_offset = 0;
    for (const auto& [clipper, trafo] : object_clippers) {
        if (int idx = clipper->is_projection_inside_cut(point); idx != -1)
            return idx_offset + idx;
        idx_offset += clipper->get_number_of_contours();
    }
    return -1;
}

bool Clipper::has_valid_contour() const
{
    return m_clp_ratio != 0.
        && std::any_of(
               object_clippers.begin(),
               object_clippers.end(),
               [](const auto& cl) { return cl.first->has_valid_contour(); }
        );
}

std::vector<Vec3d> Clipper::point_per_contour() const
{
    std::vector<Vec3d> pts;

    for (const auto& clipper : object_clippers) {
        const std::vector<Vec3d> pts_clipper = clipper.first->point_per_contour();
        pts.insert(pts.end(), pts_clipper.begin(), pts_clipper.end());
        ;
    }
    return pts;
}

void Clipper::set_position_by_ratio(double pos, bool keep_normal)
{
    using namespace Slic3r::Biz::Algorithms::BoundingBox;
    using namespace Slic3r::Biz::Algorithms::ModelObject;

    const Vec3d& bb_center = center(instance_bounding_box(*m_selected_object, *m_selected_instance))
        + Vec3d(0., 0., m_sla_shift);

    Vec3d normal = (keep_normal && m_clp) ? m_clp->get_normal() : -m_camera->forward();
    double dist   = normal.dot(bb_center);

    if (pos < 0.)
        pos = m_clp_ratio;

    m_clp_ratio = pos;
    m_clp.reset(new Biz::ClippingPlane(
        normal,
        (dist - (-m_active_inst_bb_radius) - m_clp_ratio * 2 * m_active_inst_bb_radius)
    ));

    recalculate_object_clippers();
}

void Clipper::set_range_and_pos(const Vec3d& cpl_normal, double cpl_offset, double pos)
{
    m_clp.reset(new Biz::ClippingPlane(cpl_normal, cpl_offset));
    m_clp_ratio = pos;

    recalculate_object_clippers();
}

const Biz::ClippingPlane* Clipper::get_clipping_plane(bool ignore_hide_clipped) const
{
    static const Biz::ClippingPlane no_clip = Biz::ClippingPlane::ClipsNothing();
    return (ignore_hide_clipped || m_hide_clipped) ? m_clp.get() : &no_clip;
}

void Clipper::set_behavior(bool hide_clipped, bool fill_cut, double contour_width)
{
    m_hide_clipped = hide_clipped;
    for (auto& clipper : object_clippers)
        clipper.first->set_behaviour(fill_cut, contour_width);
}

// Unprojects the mouse position on the mesh and saves hit point and normal of the facet into pos_and_normal
// Return false if no intersection was found, true otherwise.
bool Clipper::unproject_on_cut_plane(const Ray& ray, Domain::Vec3d& pos_world, bool respect_contours)
{
    // Calculate intersection with the clipping plane.
    Vec3d point = ray.origin;
    Vec3d direction = ray.direction;
    Vec3d hit;
    Vec3d normal = -m_clp->get_normal().cast<double>();
    double den = normal.dot(direction);
    if (den != 0.) {
        double t = (-m_clp->get_offset() - normal.dot(point)) / den;
        hit = (point + t * direction);
    }
    else
        return false;

    if (respect_contours)
    {
        // Do not react to clicks outside a contour (or inside a contour that is ignored)
        int cont_id = is_projection_inside_cut(hit);
        if (cont_id == -1)
            return false;
        //if (m_part_selection.valid()) {
        //    const std::vector<size_t>& ign = *m_part_selection.get_ignored_contours_ptr();
        //    if (std::find(ign.begin(), ign.end(), cont_id) != ign.end())
        //        return false;
        //}
    }

    pos_world = hit;
    return true;
}

} // namespace Slic3r::App::Scene
