#pragma once

namespace Slic3r::App::Render {

enum class ImguiFontType
{
    Regular,
    Bold,
    Italic
};

enum class Icon : wchar_t
{
    None = 0x0,
    // Our icons start at 0x2600
    PrintIconMarker = 0x2600,
    PrinterIconMarker,
    PrinterSlaIconMarker,
    FilamentIconMarker,
    MaterialIconMarker,
    CloseNotifButton,
    CloseNotifHoverButton,
    MinimalizeButton,
    MinimalizeHoverButton,
    WarningMarker,
    WarningMarkerWhite,
    ErrorMarker,
    EjectButton,
    EjectHoverButton,
    CancelButton,
    CancelHoverButton,
    //    VarLayerHeightMarker     ,
    RevertButton,

    RightArrowButton,
    RightArrowHoverButton,
    PreferencesButton,
    PreferencesHoverButton,
    //    SinkingObjectMarker      ,
    //    CustomSupportsMarker     ,
    //    CustomSeamMarker         ,
    //    MmuSegmentationMarker    ,
    PlugMarker,
    DowelMarker,
    SnapMarker,
    HorizontalHide,
    HorizontalShow,
    // Do not forget use following letters only in wstring
    DocumentationButton,
    DocumentationHoverButton,
    ClippyMarker,
    InfoMarker,
    SliderFloatEditBtnIcon,
    SliderFloatEditBtnPressedIcon,
    ClipboardBtnIcon,
    PlayButton,
    PlayHoverButton,
    PauseButton,
    PauseHoverButton,
    OpenButton,
    OpenHoverButton,
    SlaViewOriginal,
    SlaViewProcessed,
    NotificationCloseGray,

    LegendTravel,
    LegendWipe,
    LegendRetract,
    LegendDeretract,
    LegendSeams,
    LegendToolChanges,
    LegendColorChanges,
    LegendPausePrints,
    LegendCustomGCodes,
    LegendCOG,
    LegendShells,
    LegendToolMarker,
    WarningMarkerSmall,
    ExpandBtn,
    CollapseBtn,
    InfoMarkerSmall,
    PrusaSlicerIcon,

    // icons for double slider (middle size icons)
    Lock,
    LockHovered,
    Unlock,
    UnlockHovered,
    DSRevert,
    DSRevertHovered,
    DSSettings,
    DSSettingsHovered,
    // icons for double slider (small size icons)
    ErrorTick,
    ErrorTickHovered,
    PausePrint,
    PausePrintHovered,
    EditGCode,
    EditGCodeHovered,
    RemoveTick,
    RemoveTickHovered,
    DSRevertDisabled,

    // icon for multiple beds
    SliceAllBtnIcon,
    PrintIdle,
    PrintRunning,
    PrintFinished,
    WarningMarkerDisabled,
    // icon for object list
    EyeOpen,
    EyeClosed,
    SolidPartVolume,
    NegativeVolume,
    ModifierVolume,
    SupportBlocker,
    SupportModifier,
    TextSolidPartVolume,
    TextNegativeVolume,
    TextModifierVolume,
    SvgSolidPartVolume,
    SvgNegativeVolume,
    SvgModifierVolume,
    ObjectIcon,
    HRModifier,
    CustomSupports,
    CustomSeam,
    CutConnectors,
    MmSegmentation,
    Sinking,
    VariableLayerHeight,
    FuzzySkin,
    BedIcon,
    Details,
    OpenArrow,
    CloseArrow,
    ConfigContainer,
    InstancesIcon,
    OverridesMarker,
    SceneMap,
    AddBedIcon,
    DelBedIcon,
    AllBeds,
    // icon for help
    MouseLeft,
    MouseRight,
    MouseDrag,
    KeyShift,
    KeyAlt,
    KeyCtrl,
    KeyCtrlA,
    KeyEsc,
    KeyDel,
    Calculator,
    CopyForGizmo,

    // icons for toolbar
    ToolbarObjects,
    ToolbarHistory,
    ToolbarGCode,
    ToolbarGraph,
    ToolbarCut,

    // printer icons (PNGs)
    PrinterNEXT,
    CubeViewIcon,

    // sidebar icons
    SavePrint,
    SavePrintToFlash,
    SavePrintToLocal,
    SavePrintAddBookmark,

    SettingsSet,
    TobBarLoad,
    TobBarSave,
    TobBarShowUI,
    TobBarPlus,
    TopBarCross,

    // Gizmo Paint-on-Supports
    Triangle,
    Circle,
    Square,
    Hexagon,
    Sphere,
    WandMagicSparkles,
    PaintBrush,
    Prism,
    Frustum,
    DividingLine,
    Dove,

    // Gizmo Emboss
    NewBtnIcon,
    DeleteBtnIcon,
    AlignHLeftBtn,
    AlignHCenterBtn,
    AlignHRightBtn,
    AlignVTopBtn,
    AlignVCenterBtn,
    AlignVBottomBtn,

    // Gizmo Arrange
    ArrangeTopLeft,
    ArrangeTopRight,
    ArrangeBottomLeft,
    ArrangeBottomRight,
    ArrangeCenter,

    Layers,
    Infill,
    SkirtBrim,
    Support,
    Time,
    Funnel,
    Cog,
    Cogs,
    Output,
    Notes,
    CaretLeft,
    CaretUp,
    CaretDown,
    Search,
    Fan,
    AddVolume,
    Minus,
    ChevronRight,
    ChevronLeft,
    Compare,
    Hollowing,
    Pad,
    Preview,
    Move,
    Scale,
    Ellipsis,
    Cube,
    CubeAdd,
    Layout,
    LayersInspect,
    PaintSupports,
    PaintSeams,
    PaintFuzzySkin,
    PaintMultiMaterial,
    Ruler,
    Text,
    Palette,
    Scissors,
    RectangleAdd,
    Rotate,
    Simplify,
    Pin,
    PlaceOnFace,
    FlipVertically,
};

} // namespace Slic3r::App::Render
