name: Build flatpak sentry

on:
  push:
    branches:
      - master
      - release
  workflow_dispatch:

jobs:
  build_flatpak_sentry:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@lm_step_actions
    secrets: inherit
    with:
      with_asan: false
      enable_sentry:  true
      release_build: ${{ startsWith(github.ref, 'refs/tags/version_') }}
      actions_branch: lm_step_actions
