name: Build osx sentry

on:
  push:
    branches:
      - master
      - release
  workflow_dispatch:

jobs:
  build_osx_sentry:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit
    with:
      with_asan: false
      enable_sentry:  true
      release_build: ${{ startsWith(github.ref, 'refs/tags/version_') }}
      actions_branch: master
