name: Build Linux

on:
  workflow_call:

jobs:
  build_flatpak:
    name: Compile & Bundle Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    env:
      date:
      ver:
      ver_pure:      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub environment
        run: |
          ver_pure=$(grep 'set(SLIC3R_VERSION' version.inc | cut -d '"' -f2)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ver="PR-${{ github.event.number }}"
          else
            ver="$ver_pure+BOSS"
          fi
          echo "ver=$ver" >> $GITHUB_ENV
          echo "ver_pure=$ver_pure" >> $GITHUB_ENV
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Build PrusaSlicer (BOSS) Linux Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: PrusaSlicer-${{ env.ver }}+Linux-${{ env.date }}.flatpak
          manifest-path: .flatpak/io.github.mjonuschat.PrusaSlicer.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false

      - uses: actions/upload-artifact@v4
        with:
          name: PrusaSlicer-${{ env.ver }}+Linux-${{ env.date }}
          path: PrusaSlicer-${{ env.ver }}+Linux-${{ env.date }}.flatpak
          if-no-files-found: error
