name: Build osx

on:
  push:
    branches:
      - master # disable flatpak for slic3r3 for now (we require to update OSX to have C++ 20 required by Yoga)
  workflow_dispatch:

jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@slic3r3_prototype
    secrets: inherit
    with:
      actions_branch: slic3r3_prototype
