name: Build flatpak

on:
  push:
    branches:
      - master # disable flatpak for slic3r3 for now (we need to record transitive deps, so these get downloaded when build flatpak
  workflow_dispatch:

jobs:
  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@slic3r3_prototype
    secrets: inherit
    with:
      actions_branch: slic3r3_prototype
