name: Build all

on:
  push:
    branches:
     - boss
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'resources/**'
     - ".github/workflows/*.yml"
     - "build_release_linux.sh"
     - "build_release_macos.sh"
     - "build_win.bat"

  pull_request:
    branches:
     - boss
     - release/*
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/*.yml"

  workflow_dispatch: # allows for manual dispatch
    inputs:
      build-deps-only:
        description: 'Only build dependencies (bypasses caching)'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  build_all:
    name: Build All
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-14
            arch: arm64
          - os: macos-13
            arch: x86_64
          - os: windows-latest
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
    secrets: inherit
  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: build_all
    secrets: inherit
    permissions:
      contents: write    
