name: Build without GUI

on:
  workflow_dispatch:

jobs:
  build_nogui:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_nogui.yml@lm_step_actions
    secrets: inherit
    with:
      actions_branch: lm_step_actions
