name: Build osx asan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_osx_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@slic3r3_prototype
    secrets: inherit
    with:
      with_asan: true
      actions_branch: slic3r3_prototype
