name: Release Lifecycle

on:
  release:
    types: [published, unpublished]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-version:
    uses: mjonuschat/prusaslicer-ci/.github/workflows/publish_version.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
