name: Create Release

on:
  workflow_call:

jobs:
  create_nightly:
    name: Create Nightly Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/boss'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: PrusaSlicer-*BOSS* 
          merge-multiple: true

      - run: ls -la PrusaSlicer-*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "PrusaSlicer-*BOSS+win64*,PrusaSlicer-*BOSS+MacOS-universal*,PrusaSlicer-*+BOSS+Linux*"
          allowUpdates: true
          artifactErrorsFailBuild: true
          bodyFile: ${{ github.workspace }}/.github/RELEASE_TEMPLATE.md
          commit: ${{ github.sha }}
          draft: true
          makeLatest: false
          name: PrusaSlicer+BOSS Development Build
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          removeArtifacts: true
          replacesArtifacts: true
          tag: nightly

  create_release:
    name: Create PrusaSlicer (BOSS) GitHub Release
    runs-on: ubuntu-latest
    env:
      ver_pure:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PrusaSlicer Version
        run: |
          ver_pure=$(grep 'set(SLIC3R_VERSION' version.inc | cut -d '"' -f2)
          echo "ver_pure=$ver_pure" >> $GITHUB_ENV

      - name: Download PrusaSlicer (BOSS) Build Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: PrusaSlicer-*BOSS* 
          merge-multiple: true

      - name: Create PrusaSlicer (BOSS) GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PrusaSlicer-*BOSS+win64*,PrusaSlicer-*BOSS+MacOS-universal*,PrusaSlicer-*+BOSS+Linux*"
          allowUpdates: false
          artifactErrorsFailBuild: true
          bodyFile: ${{ github.workspace }}/.github/RELEASE_TEMPLATE.md
          commit: ${{ github.sha }}
          draft: true
          makeLatest: true
          name: PrusaSlicer ${{ env.ver_pure }} (BOSS)
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          removeArtifacts: true
          replacesArtifacts: true
          skipIfReleaseExists: true
          updateOnlyUnreleased: true
          tag: version_${{ env.ver_pure }}+boss
